debug: true

spring:
  application:
    name: CONNECTION
  datasource:
    db1:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/test01?serverTimezone=UTC
      username: root
      password: 123456
      type: com.alibaba.druid.pool.DruidDataSource
    db2:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://11.11.11.11:3306/test02?serverTimezone=UTC
      username: root
      password: 123456
      type: com.alibaba.druid.pool.DruidDataSource

  redis1:
    timeout: 600000
    database: 0
    host: localhost
    password: 123456789
    port: 6379
    lettuce:
      pool:
        max-active: 1000 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 3 # 连接池中的最小空闲连接
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
  redis2:
    timeout: 600000
    database: 10
    port: 6379 #单实例redis用这个配置
    password: Redis@123
    cluster: #集群用这个配置
      nodes:
        - 127.0.0.1:7011
        - 127.0.0.1:7012
        - 127.0.0.1:7013
        - 127.0.0.1:7014
        - 127.0.0.1:7015
        - 127.0.0.1:7016
      max-redirects: 2 #获取失败 最大重定向次数
    lettuce:
      pool:
        max-active: 1000
        max-idle: 10
        min-idle: 3
        max-wait: -1
  redis3: # 一主2从192.168.10.1:6379,192.168.10.2:6379,192.168.10.3:6379。三哨兵192.168.10.1:26379,192.168.10.2:26379,192.168.10.3:26379
    timeout: 600000
    database: 0
    host: 192.168.10.1 # 主节点的master
    password: 123456789
    port: 6379 # 主节点的master端口
    lettuce:
      pool:
        max-active: 1000
        max-idle: 10
        min-idle: 3
        max-wait: -1
    sentinel:
      master: mymaster
      nodes:
        - 192.168.10.1:26379
        - 192.168.10.2:26379
        - 192.168.10.3:26379

logging:
  level:
    root: debug
    org.springframework: debug
    com.glf: debug