debug: true

spring:
  application:
    name: glf-service2-application
  datasource:
    dynamic:
      primary: datasource1 #设置默认的数据源或者数据源组,默认值即为datasource1
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        datasource1:
          url: jdbc:mysql://localhost:3306/test01
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
        datasource2:
          url: jdbc:mysql://localhost:3306/test02
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
